In [1]:
import numpy as np

In [2]:
a = np.array([[70.0, 1.0, 0.0],[60.0, -1.0, 1.0],[40.0, 0.0, -1.0]])
b = np.array([636.7, 518.6, 307.4])
print(a)
print(b)
print(np.linalg.solve(a, b))

[[70.  1.  0.]
 [60. -1.  1.]
 [40.  0. -1.]]
[636.7 518.6 307.4]
[ 8.60411765 34.41176471 36.76470588]
